package com.aicontent.globalInsightApp.entity.modelAll

data class Currencies(
    val AED: AED,
    val AFN: AFN,
    val ALL: ALL,
    val AMD: AMD,
    val ANG: ANG,
    val AOA: AOA,
    val ARS: ARS,
    val AUD: AUD,
    val AWG: AWG,
    val AZN: AZN,
    val BAM: BAM,
    val BBD: BBD,
    val BDT: BDT,
    val BGN: BGN,
    val BHD: BHD,
    val BIF: BIF,
    val BMD: BMD,
    val BND: BND,
    val BOB: BOB,
    val BRL: BRL,
    val BSD: BSD,
    val BTN: BTN,
    val BWP: BWP,
    val BYN: BYN,
    val BZD: BZD,
    val CAD: CAD,
    val CDF: CDF,
    val CHF: CHF,
    val CKD: CKD,
    val CLP: CLP,
    val CNY: CNY,
    val COP: COP,
    val CRC: CRC,
    val CUC: CUC,
    val CUP: CUP,
    val CVE: CVE,
    val CZK: CZK,
    val DJF: DJF,
    val DKK: DKK,
    val DOP: DOP,
    val DZD: DZD,
    val EGP: EGP,
    val ERN: ERN,
    val ETB: ETB,
    val EUR: EUR,
    val FJD: FJD,
    val FKP: FKP,
    val FOK: FOK,
    val GBP: GBP,
    val GEL: GEL,
    val GGP: GGP,
    val GHS: GHS,
    val GIP: GIP,
    val GMD: GMD,
    val GNF: GNF,
    val GTQ: GTQ,
    val GYD: GYD,
    val HKD: HKD,
    val HNL: HNL,
    val HTG: HTG,
    val HUF: HUF,
    val IDR: IDR,
    val ILS: ILS,
    val IMP: IMP,
    val INR: INR,
    val IQD: IQD,
    val IRR: IRR,
    val ISK: ISK,
    val JEP: JEP,
    val JMD: JMD,
    val JOD: JOD,
    val JPY: JPY,
    val KES: KES,
    val KGS: KGS,
    val KHR: KHR,
    val KID: KID,
    val KMF: KMF,
    val KPW: KPW,
    val KRW: KRW,
    val KWD: KWD,
    val KYD: KYD,
    val KZT: KZT,
    val LAK: LAK,
    val LBP: LBP,
    val LKR: LKR,
    val LRD: LRD,
    val LSL: LSL,
    val LYD: LYD,
    val MAD: MAD,
    val MDL: MDL,
    val MGA: MGA,
    val MKD: MKD,
    val MMK: MMK,
    val MNT: MNT,
    val MOP: MOP,
    val MRU: MRU,
    val MUR: MUR,
    val MVR: MVR,
    val MWK: MWK,
    val MXN: MXN,
    val MYR: MYR,
    val MZN: MZN,
    val NAD: NAD,
    val NGN: NGN,
    val NIO: NIO,
    val NOK: NOK,
    val NPR: NPR,
    val NZD: NZD,
    val OMR: OMR,
    val PAB: PAB,
    val PEN: PEN,
    val PGK: PGK,
    val PHP: PHP,
    val PKR: PKR,
    val PLN: PLN,
    val PYG: PYG,
    val QAR: QAR,
    val RON: RON,
    val RSD: RSD,
    val RUB: RUB,
    val RWF: RWF,
    val SAR: SAR,
    val SBD: SBD,
    val SCR: SCR,
    val SDG: SDG,
    val SEK: SEK,
    val SGD: SGD,
    val SHP: SHP,
    val SLL: SLL,
    val SOS: SOS,
    val SRD: SRD,
    val SSP: SSP,
    val STN: STN,
    val SYP: SYP,
    val SZL: SZL,
    val THB: THB,
    val TJS: TJS,
    val TMT: TMT,
    val TND: TND,
    val TOP: TOP,
    val TRY: TRY,
    val TTD: TTD,
    val TVD: TVD,
    val TWD: TWD,
    val TZS: TZS,
    val UAH: UAH,
    val UGX: UGX,
    val USD: USD,
    val UYU: UYU,
    val UZS: UZS,
    val VES: VES,
    val VND: VND,
    val VUV: VUV,
    val WST: WST,
    val XAF: XAF,
    val XCD: XCD,
    val XOF: XOF,
    val XPF: XPF,
    val YER: YER,
    val ZAR: ZAR,
    val ZMW: ZMW,
    val ZWL: ZWL
)

//data class Currencies(
//    val AED: AED,
//    val AFN: com.aicontent.myapplication.entity.modelAll.AFN,
//    val ALL: com.aicontent.myapplication.entity.modelAll.ALL,
//    val AMD: com.aicontent.myapplication.entity.modelAll.AMD,
//    val ANG: com.aicontent.myapplication.entity.modelAll.ANG,
//    val AOA: com.aicontent.myapplication.entity.modelAll.AOA,
//    val ARS: com.aicontent.myapplication.entity.modelAll.ARS,
//    val AUD: com.aicontent.myapplication.entity.modelAll.AUD,
//    val AWG: com.aicontent.myapplication.entity.modelAll.AWG,
//    val AZN: com.aicontent.myapplication.entity.modelAll.AZN,
//    val BAM: com.aicontent.myapplication.entity.modelAll.BAM,
//    val BBD: com.aicontent.myapplication.entity.modelAll.BBD,
//    val BDT: com.aicontent.myapplication.entity.modelAll.BDT,
//    val BGN: com.aicontent.myapplication.entity.modelAll.BGN,
//    val BHD: com.aicontent.myapplication.entity.modelAll.BHD,
//    val BIF: com.aicontent.myapplication.entity.modelAll.BIF,
//    val BMD: com.aicontent.myapplication.entity.modelAll.BMD,
//    val BND: com.aicontent.myapplication.entity.modelAll.BND,
//    val BOB: com.aicontent.myapplication.entity.modelAll.BOB,
//    val BRL: com.aicontent.myapplication.entity.modelAll.BRL,
//    val BSD: com.aicontent.myapplication.entity.modelAll.BSD,
//    val BTN: com.aicontent.myapplication.entity.modelAll.BTN,
//    val BWP: com.aicontent.myapplication.entity.modelAll.BWP,
//    val BYN: com.aicontent.myapplication.entity.modelAll.BYN,
//    val BZD: com.aicontent.myapplication.entity.modelAll.BZD,
//    val CAD: com.aicontent.myapplication.entity.modelAll.CAD,
//    val CDF: com.aicontent.myapplication.entity.modelAll.CDF,
//    val CHF: com.aicontent.myapplication.entity.modelAll.CHF,
//    val CKD: com.aicontent.myapplication.entity.modelAll.CKD,
//    val CLP: com.aicontent.myapplication.entity.modelAll.CLP,
//    val CNY: com.aicontent.myapplication.entity.modelAll.CNY,
//    val COP: com.aicontent.myapplication.entity.modelAll.COP,
//    val CRC: com.aicontent.myapplication.entity.modelAll.CRC,
//    val CUC: com.aicontent.myapplication.entity.modelAll.CUC,
//    val CUP: com.aicontent.myapplication.entity.modelAll.CUP,
//    val CVE: com.aicontent.myapplication.entity.modelAll.CVE,
//    val CZK: com.aicontent.myapplication.entity.modelAll.CZK,
//    val DJF: com.aicontent.myapplication.entity.modelAll.DJF,
//    val DKK: com.aicontent.myapplication.entity.modelAll.DKK,
//    val DOP: com.aicontent.myapplication.entity.modelAll.DOP,
//    val DZD: com.aicontent.myapplication.entity.modelAll.DZD,
//    val EGP: com.aicontent.myapplication.entity.modelAll.EGP,
//    val ERN: com.aicontent.myapplication.entity.modelAll.ERN,
//    val ETB: com.aicontent.myapplication.entity.modelAll.ETB,
//    val EUR: com.aicontent.myapplication.entity.modelAll.EUR,
//    val FJD: com.aicontent.myapplication.entity.modelAll.FJD,
//    val FKP: com.aicontent.myapplication.entity.modelAll.FKP,
//    val FOK: com.aicontent.myapplication.entity.modelAll.FOK,
//    val GBP: com.aicontent.myapplication.entity.modelAll.GBP,
//    val GEL: com.aicontent.myapplication.entity.modelAll.GEL,
//    val GGP: com.aicontent.myapplication.entity.modelAll.GGP,
//    val GHS: com.aicontent.myapplication.entity.modelAll.GHS,
//    val GIP: com.aicontent.myapplication.entity.modelAll.GIP,
//    val GMD: com.aicontent.myapplication.entity.modelAll.GMD,
//    val GNF: com.aicontent.myapplication.entity.modelAll.GNF,
//    val GTQ: com.aicontent.myapplication.entity.modelAll.GTQ,
//    val GYD: com.aicontent.myapplication.entity.modelAll.GYD,
//    val HKD: com.aicontent.myapplication.entity.modelAll.HKD,
//    val HNL: com.aicontent.myapplication.entity.modelAll.HNL,
//    val HTG: com.aicontent.myapplication.entity.modelAll.HTG,
//    val HUF: com.aicontent.myapplication.entity.modelAll.HUF,
//    val IDR: com.aicontent.myapplication.entity.modelAll.IDR,
//    val ILS: com.aicontent.myapplication.entity.modelAll.ILS,
//    val IMP: com.aicontent.myapplication.entity.modelAll.IMP,
//    val INR: com.aicontent.myapplication.entity.modelAll.INR,
//    val IQD: com.aicontent.myapplication.entity.modelAll.IQD,
//    val IRR: com.aicontent.myapplication.entity.modelAll.IRR,
//    val ISK: com.aicontent.myapplication.entity.modelAll.ISK,
//    val JEP: com.aicontent.myapplication.entity.modelAll.JEP,
//    val JMD: com.aicontent.myapplication.entity.modelAll.JMD,
//    val JOD: com.aicontent.myapplication.entity.modelAll.JOD,
//    val JPY: com.aicontent.myapplication.entity.modelAll.JPY,
//    val KES: com.aicontent.myapplication.entity.modelAll.KES,
//    val KGS: com.aicontent.myapplication.entity.modelAll.KGS,
//    val KHR: com.aicontent.myapplication.entity.modelAll.KHR,
//    val KID: com.aicontent.myapplication.entity.modelAll.KID,
//    val KMF: com.aicontent.myapplication.entity.modelAll.KMF,
//    val KPW: com.aicontent.myapplication.entity.modelAll.KPW,
//    val KRW: com.aicontent.myapplication.entity.modelAll.KRW,
//    val KWD: com.aicontent.myapplication.entity.modelAll.KWD,
//    val KYD: com.aicontent.myapplication.entity.modelAll.KYD,
//    val KZT: com.aicontent.myapplication.entity.modelAll.KZT,
//    val LAK: com.aicontent.myapplication.entity.modelAll.LAK,
//    val LBP: com.aicontent.myapplication.entity.modelAll.LBP,
//    val LKR: com.aicontent.myapplication.entity.modelAll.LKR,
//    val LRD: com.aicontent.myapplication.entity.modelAll.LRD,
//    val LSL: com.aicontent.myapplication.entity.modelAll.LSL,
//    val LYD: com.aicontent.myapplication.entity.modelAll.LYD,
//    val MAD: com.aicontent.myapplication.entity.modelAll.MAD,
//    val MDL: com.aicontent.myapplication.entity.modelAll.MDL,
//    val MGA: com.aicontent.myapplication.entity.modelAll.MGA,
//    val MKD: com.aicontent.myapplication.entity.modelAll.MKD,
//    val MMK: com.aicontent.myapplication.entity.modelAll.MMK,
//    val MNT: com.aicontent.myapplication.entity.modelAll.MNT,
//    val MOP: com.aicontent.myapplication.entity.modelAll.MOP,
//    val MRU: com.aicontent.myapplication.entity.modelAll.MRU,
//    val MUR: com.aicontent.myapplication.entity.modelAll.MUR,
//    val MVR: com.aicontent.myapplication.entity.modelAll.MVR,
//    val MWK: com.aicontent.myapplication.entity.modelAll.MWK,
//    val MXN: com.aicontent.myapplication.entity.modelAll.MXN,
//    val MYR: com.aicontent.myapplication.entity.modelAll.MYR,
//    val MZN: com.aicontent.myapplication.entity.modelAll.MZN,
//    val NAD: com.aicontent.myapplication.entity.modelAll.NAD,
//    val NGN: com.aicontent.myapplication.entity.modelAll.NGN,
//    val NIO: com.aicontent.myapplication.entity.modelAll.NIO,
//    val NOK: com.aicontent.myapplication.entity.modelAll.NOK,
//    val NPR: com.aicontent.myapplication.entity.modelAll.NPR,
//    val NZD: com.aicontent.myapplication.entity.modelAll.NZD,
//    val OMR: com.aicontent.myapplication.entity.modelAll.OMR,
//    val PAB: com.aicontent.myapplication.entity.modelAll.PAB,
//    val PEN: com.aicontent.myapplication.entity.modelAll.PEN,
//    val PGK: com.aicontent.myapplication.entity.modelAll.PGK,
//    val PHP: com.aicontent.myapplication.entity.modelAll.PHP,
//    val PKR: com.aicontent.myapplication.entity.modelAll.PKR,
//    val PLN: com.aicontent.myapplication.entity.modelAll.PLN,
//    val PYG: com.aicontent.myapplication.entity.modelAll.PYG,
//    val QAR: com.aicontent.myapplication.entity.modelAll.QAR,
//    val RON: com.aicontent.myapplication.entity.modelAll.RON,
//    val RSD: com.aicontent.myapplication.entity.modelAll.RSD,
//    val RUB: com.aicontent.myapplication.entity.modelAll.RUB,
//    val RWF: com.aicontent.myapplication.entity.modelAll.RWF,
//    val SAR: com.aicontent.myapplication.entity.modelAll.SAR,
//    val SBD: com.aicontent.myapplication.entity.modelAll.SBD,
//    val SCR: com.aicontent.myapplication.entity.modelAll.SCR,
//    val SDG: com.aicontent.myapplication.entity.modelAll.SDG,
//    val SEK: com.aicontent.myapplication.entity.modelAll.SEK,
//    val SGD: com.aicontent.myapplication.entity.modelAll.SGD,
//    val SHP: com.aicontent.myapplication.entity.modelAll.SHP,
//    val SLL: com.aicontent.myapplication.entity.modelAll.SLL,
//    val SOS: com.aicontent.myapplication.entity.modelAll.SOS,
//    val SRD: com.aicontent.myapplication.entity.modelAll.SRD,
//    val SSP: com.aicontent.myapplication.entity.modelAll.SSP,
//    val STN: com.aicontent.myapplication.entity.modelAll.STN,
//    val SYP: com.aicontent.myapplication.entity.modelAll.SYP,
//    val SZL: com.aicontent.myapplication.entity.modelAll.SZL,
//    val THB: com.aicontent.myapplication.entity.modelAll.THB,
//    val TJS: com.aicontent.myapplication.entity.modelAll.TJS,
//    val TMT: com.aicontent.myapplication.entity.modelAll.TMT,
//    val TND: com.aicontent.myapplication.entity.modelAll.TND,
//    val TOP: com.aicontent.myapplication.entity.modelAll.TOP,
//    val TRY: com.aicontent.myapplication.entity.modelAll.TRY,
//    val TTD: com.aicontent.myapplication.entity.modelAll.TTD,
//    val TVD: com.aicontent.myapplication.entity.modelAll.TVD,
//    val TWD: com.aicontent.myapplication.entity.modelAll.TWD,
//    val TZS: com.aicontent.myapplication.entity.modelAll.TZS,
//    val UAH: com.aicontent.myapplication.entity.modelAll.UAH,
//    val UGX: com.aicontent.myapplication.entity.modelAll.UGX,
//    val USD: com.aicontent.myapplication.entity.modelAll.USD,
//    val UYU: com.aicontent.myapplication.entity.modelAll.UYU,
//    val UZS: com.aicontent.myapplication.entity.modelAll.UZS,
//    val VES: com.aicontent.myapplication.entity.modelAll.VES,
//    val VND: com.aicontent.myapplication.entity.modelAll.VND,
//    val VUV: com.aicontent.myapplication.entity.modelAll.VUV,
//    val WST: com.aicontent.myapplication.entity.modelAll.WST,
//    val XAF: com.aicontent.myapplication.entity.modelAll.XAF,
//    val XCD: com.aicontent.myapplication.entity.modelAll.XCD,
//    val XOF: com.aicontent.myapplication.entity.modelAll.XOF,
//    val XPF: com.aicontent.myapplication.entity.modelAll.XPF,
//    val YER: com.aicontent.myapplication.entity.modelAll.YER,
//    val ZAR: com.aicontent.myapplication.entity.modelAll.ZAR,
//    val ZMW: com.aicontent.myapplication.entity.modelAll.ZMW,
//    val ZWL: com.aicontent.myapplication.entity.modelAll.ZWL
//)